# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget pdalcpp pdal_util)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target pdalcpp
add_library(pdalcpp SHARED IMPORTED)

# Create imported target pdal_util
add_library(pdal_util SHARED IMPORTED)

# Import target "pdalcpp" for configuration "Debug"
set_property(TARGET pdalcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(pdalcpp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/Debug/pdalcpp.lib"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/Debug/pdalcpp.dll"
  )

# Import target "pdal_util" for configuration "Debug"
set_property(TARGET pdal_util APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(pdal_util PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/Debug/pdal_util.lib"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/Debug/pdal_util.dll"
  )

# Import target "pdalcpp" for configuration "Release"
set_property(TARGET pdalcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pdalcpp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/Release/pdalcpp.lib"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/Release/pdalcpp.dll"
  )

# Import target "pdal_util" for configuration "Release"
set_property(TARGET pdal_util APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pdal_util PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/Release/pdal_util.lib"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/Release/pdal_util.dll"
  )

# Import target "pdalcpp" for configuration "MinSizeRel"
set_property(TARGET pdalcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(pdalcpp PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/MinSizeRel/pdalcpp.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/MinSizeRel/pdalcpp.dll"
  )

# Import target "pdal_util" for configuration "MinSizeRel"
set_property(TARGET pdal_util APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(pdal_util PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/MinSizeRel/pdal_util.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/MinSizeRel/pdal_util.dll"
  )

# Import target "pdalcpp" for configuration "RelWithDebInfo"
set_property(TARGET pdalcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(pdalcpp PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/RelWithDebInfo/pdalcpp.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/RelWithDebInfo/pdalcpp.dll"
  )

# Import target "pdal_util" for configuration "RelWithDebInfo"
set_property(TARGET pdal_util APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(pdal_util PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Development/op3d_active/PDAL-2.1.0/msvc/lib/RelWithDebInfo/pdal_util.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/PDAL-2.1.0/msvc/bin/RelWithDebInfo/pdal_util.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
